ep_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.authtoken import views

admin.site.site_header = 'Energy Aggregator Admin'
admin.site.site_title = 'Energy Aggregator'
admin.site.index_title = 'Energy Aggregator Index'

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^api-token-auth/', views.obtain_auth_token),

    # url(r'^heatrank/', include('heatrank.urls', namespace="heatrank")),
    url(r'^api/', include('ep.urls.api', namespace='api')),

    # url(r'^accounts/', include('registration.backends.default.urls')),



    # @todo - this pattern swallows all other urls - fix
    url(r'^', include('ep.urls.web', namespace="web")),

    url(r'^apidocs/', include('rest_framework_docs.urls')),
]

prefect/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from ep.views import NodeListView, DeviceParameterDetailView
from prefect.views import DeviceDetailView

__author__ = 'schien'

urlpatterns = [
    url(r'^(?P<site>[\w]+)/(?P<prefect_id>[0-9]+)$',
        login_required(DeviceDetailView.as_view()),
        name='device-detail'),
    url(r'^devices$', login_required(NodeListView.as_view()), name='prefectdevice-list'),
    url(r'^(?P<site>[\w]+)$', login_required(NodeListView.as_view()),
        name='prefectdevice-list'),
    url(r'^device/(?P<device_parameter_id>[0-9]+)$',
        login_required(DeviceParameterDetailView.as_view()),
        name='device-parameter-detail'),
]

ep/models.py
import logging
from decimal import Decimal
from datetime import datetime

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

import ep
import requests
import simplejson as json
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.dateparse import parse_datetime
from influxdb import InfluxDBClient
from weekday_field.fields import WeekdayField

logger = logging.getLogger(__name__)


class BaseEntity(models.Model):
    class Meta:
        abstract = True

    def get_content_type(self):
        return ContentType.objects.get_for_model(self).id


class Unit(object):
    CELSIUS = 'C'
    WATTS = 'W'
    NO_UNIT = 'N'
    PERCENT = '%'
    BOOL = 'B'
    SECONDS = 'S'
    KWH = 'K'


class Site(BaseEntity):
    name = models.CharField(max_length=50, default='site', null=False, unique=True)

    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    actions = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.name


class SiteProperty(models.Model):
    site = models.ForeignKey(Site, related_name='properties')
    key = models.CharField(max_length=50, null=True)
    value = models.CharField(max_length=200, null=True)

    def __str__(self):
        return "%s: %s" % (self.key, self.value)


class Vendor(models.Model):
    name = models.CharField(max_length=80, null=False)

    def __str__(self):
        return "{name}".format(name=self.name)


class Gateway(BaseEntity):
    site = models.ForeignKey(Site, related_name='gateways')
    vendor = models.ForeignKey(Vendor, related_name='gateways')
    external_id = models.CharField(max_length=200, blank=True, null=True, default='default', unique=True)

    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    actions = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return "{site}: {id}".format(site=self.site, id=self.external_id)


SECURE_SERVER_NAME = 'secure-server-name'


class GatewayProperty(models.Model):
    gateway = models.ForeignKey(Gateway, related_name='properties')
    key = models.CharField(max_length=50, null=True)
    value = models.CharField(max_length=200, null=True)

    def __str__(self):
        return "%s: %s" % (self.key, self.value)


class Node(BaseEntity):
    gateway = models.ForeignKey(Gateway, related_name='nodes')
    vendor = models.ForeignKey(Vendor, related_name='nodes')
    space_name = models.CharField(max_length=100, null=True)
    floor = models.CharField(max_length=10, null=True)
    building = models.CharField(max_length=50, null=True)
    external_id = models.CharField(max_length=200, null=True, default='default', db_index=True)

    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    actions = GenericForeignKey('content_type', 'object_id')

    class Meta:
        unique_together = ('gateway', 'external_id',)

    def __str__(self):
        result = "[{id}]: {external_id}".format(id=self.id, external_id=self.external_id)
        if self.space_name is not None:
            result += " \"{}\"".format(self.space_name)
        return result


class NodeProperty(models.Model):
    node = models.ForeignKey(Node, related_name='properties')
    key = models.CharField(max_length=50, null=True)
    value = models.CharField(max_length=200, null=True)

    def __str__(self):
        return "%s: %s" % (self.key, self.value)


class DeviceType(models.Model):
    code = models.CharField(max_length=50, null=False, db_index=True)
    description = models.CharField(max_length=100, null=True)

    def __str__(self):
        result = "{}".format(self.code)
        if self.description is not None:
            result += " {}".format(self.description)
        return result


class Device(BaseEntity):
    node = models.ForeignKey(Node, related_name='devices')
    vendor = models.ForeignKey(Vendor, related_name='devices')
    type = models.ForeignKey(DeviceType, related_name='devices')
    name = models.CharField(max_length=50, null=True)
    external_id = models.CharField(max_length=200, null=True, db_index=True)
    precedence = models.IntegerField(null=True, default=50)

    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    actions = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        result = "[{id}]".format(id=self.id)

        if self.type is not None:
            result += " {type}".format(type=self.type)

        if self.name is not None:
            result += " {name}".format(name=self.name)
        else:
            if self.external_id is not None:
                result += " {external_id}".format(external_id=self.external_id)

        return result

    @property
    def last_update_time(self):
        """
        Synthesise this from the DP with the last update time
        :return:
        """
        lut = None
        for dp in self.parameters.all():
            latest = dp.measurements.latest()
            if latest:
                latest_ts = parse_datetime(latest['time'])
                if not lut or lut < latest_ts:
                    lut = latest_ts
        return lut.strftime('%x %X')


class DeviceParameterType(models.Model):
    code = models.CharField(max_length=80, null=False, db_index=True)
    description = models.CharField(max_length=100, null=True)

    def __str__(self):
        return "{} {}".format(self.code, self.description)


class DeviceParameter(BaseEntity):
    device = models.ForeignKey(Device, related_name='parameters')
    type = models.ForeignKey(DeviceParameterType, related_name='device_parameters')
    unit = models.CharField(max_length=80, null=True)

    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    actions = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        result = "[{id}] (device {device})".format(id=self.id, device=self.device.external_id)
        if self.type is not None:
            result += "[{type}]".format(type=self.type)
        return result

    @property
    def measurements(self):
        return DPMeasurements(device_parameter=self)

    @property
    def last_update_time(self):
        latest = self.measurements.latest()
        if latest:
            latest_ts = parse_datetime(latest['time'])
            return latest_ts.strftime('%x %X')


class StateChangeEvent(models.Model):
    device_property = models.ForeignKey(DeviceParameter)

    ON_DEVICE = 'OD'
    EBE = 'EB'
    API = 'AP'
    SCHEDULE = 'SC'

    TRIGGER_CHOICES = (
        (ON_DEVICE, 'C'),
        (SCHEDULE, 'A'),
        (EBE, 'E'),

    )
    trigger = models.CharField(max_length=2,
                               choices=TRIGGER_CHOICES)

    date_time = models.DateTimeField()

    previous_value = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    new_value = models.DecimalField(max_digits=7, decimal_places=2, null=True)

    class Meta:
        ordering = ['-date_time']
        get_latest_by = "date_time"


class Tariff(models.Model):
    name = models.CharField(max_length=50, null=True)
    enabled = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Band(models.Model):
    tariff = models.ForeignKey(Tariff, related_name='bands')

    valid_from = models.DateField()
    valid_to = models.DateField()

    # @todo there is a breaking dependency on SubFieldBase which was removed in django 1.10.
    # @todo either replace this or fix this
    weekdays = WeekdayField()

    start_time = models.TimeField()
    end_time = models.TimeField()

    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name if self.name else "{} - {}".format(self.start_time, self.end_time)


class TariffBandProperty(models.Model):
    band = models.ForeignKey(Band, related_name='properties')
    key = models.CharField(max_length=50, null=True)
    value = models.CharField(max_length=200, null=True)

    def __str__(self):
        return "%s: %s" % (self.key, self.value)


class ScheduleDeviceParameterGroup(models.Model):
    """
    A schedule is implemented with :func:`djcelery.PeriodicTasks` and a :func:`scheduled_device_state_change` task.
    All device parameters in a ScheduleDeviceParameterGroup will have their values set to the target values defined in
    the PeriodicTask.

    E.g. if there are devices A and B in the schedule and the schedule has two SSC's X and Y with
    X.scheduled_time = Monday 9:00 am with X.target_value = 80 and
    Y.scheduled_time = Monday 16:00 am with Y.target_value = 10

    then A and B will change their target values to 80 on Monday morning and back to 10 on Monday afternoon.
    """
    device_parameters = models.ManyToManyField(DeviceParameter,
                                               related_name='schedule',
                                               # @todo fix this
                                               # limit_choices_to={'device__node__gateway__site': Site.objects.get(
                                               #     name=secure_site_name).id}
                                               )

    # name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return "[{id}] {name}".format(id=self.id, name=self.name)


session = requests.Session()


class TSMeasurements(object):
    MEASUREMENT_NAME = 'TS'
    DEFAULT_TAG_NAME = None
    DEFAULT_TAG_VALUE = None

    def __init__(self, measurement_name, tag_name=None, tag_value=None):

ep/views.py
# Create your views here.
import logging

from django.views.generic import TemplateView
from django.views.generic.list import ListView

from ep.models import Node, DeviceParameter, Gateway

logger = logging.getLogger(__name__)


class NodeListView(ListView):
    queryset = Node.objects.all()

    def get_queryset(self):
        if 'site' in self.kwargs:
            gateways = Gateway.objects.filter(site=self.kwargs['site'])
            return Node.objects.filter(gateway__site_id__in=gateways)

        else:
            return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super(NodeListView, self).get_context_data(**kwargs)
        return context


class DeviceDetailView(TemplateView):
    template_name = 'ep/device_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DeviceDetailView, self).get_context_data(**kwargs)
        node_id = kwargs['pk']
        dev = Node.objects.get(node_id)
        context['node'] = dev
        return context


class DeviceParameterDetailView(TemplateView):
    template_name = 'ep/device_param_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DeviceParameterDetailView, self).get_context_data(**kwargs)
        param_id = self.kwargs['device_parameter_id']
        device_param = DeviceParameter.objects.get(id=param_id)

        context['device_param'] = device_param
        return context


class SimpleVisView(TemplateView):
    # chose template
    template_name = 'ep_vis/IndivNode.html'

    def get_context_data(self, **kwargs):
    #     # define json var data, metadata, etc
    #     context = super(DeviceParameterDetailView, self).get_context_data(**kwargs)
    #     param_id = self.kwargs['device_parameter_id']
    #     device_param = DeviceParameter.objects.get(id=param_id)
    #
    #     data_var = ['data':'
    # {
    #     "Temperature": 18.8,
    #     "Presence": 0,
    #     "ProgramName": "Unoccupied",
    #     "DateTimeRecieved": "2016-06-23 00:09:43",
    #     "TempAdjusted": 0,
    #     "L2Relay": 0,
    #     "EnergyWh": 0.0,
    #     "TempSetPoint": 14.0
    # }']
    #
    #     context['data'] = data_var
    #     context['metadata'] = device_param

        return super().get_context_data()

ep/templates/ep/device_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/index.css" %}'>
    <link rel="stylesheet" href='{% static "css/charts.css" %}'>
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script src='{% static "js/charts.js" %}'></script>

    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>#}
    {#    <script src='{% static "lib/js/nv.d3.min.js" %}'></script>#}
    {#    <link rel="stylesheet" href='{% static "lib/css/nv.d3.min.css" %}'>#}
{% endblock css %}

{% block page_title %}Device{% endblock %}
{% block body_class %}{{ block.super }}{% endblock %}

{% block content %}

    <h1>Prefect Device {{ node }}</h1>

    <table>
        <tr>
            <td>Site</td>
            <td>{{ node.site }}</td>
        </tr>

        <tr>
            <td>Room Name</td>
            <td>{{ node.space_name }}</td>
        </tr>

    </table>

    <div id="chart">

    </div>

    <script type="text/javascript">
        {% url 'api:device_measurements' device.site device.prefect_id as api_endpoint %}
        document.body.onload = function () {
            drawTemperatureChart('{{ api_endpoint }}');
        }
    </script>

{% endblock content %}

ep/templates/ep/device_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block css %}
    <link rel="stylesheet" href='{% static "css/index.css" %}'>
{% endblock css %}
{% block page_title %}Energy Portal Home{% endblock %}
{% block body_class %}{{ block.super }}{% endblock %}

{% block content %}

    <h1>Prefect Devices</h1>
    <ul>
        {% for device in object_list %}
            <li><a href="{% url 'web:device-detail' device.site device.prefect_id %}">{{ device }}</a></li>

        {% empty %}
            <li>No devices recorded.</li>
        {% endfor %}
    </ul>
{% endblock content %}

ep/templates/ep/device_param_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/index.css" %}'>
    <link rel="stylesheet" href='{% static "css/charts.css" %}'>
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script src='{% static "js/charts.js" %}'></script>

    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>#}
    {#    <script src='{% static "lib/js/nv.d3.min.js" %}'></script>#}
    {#    <link rel="stylesheet" href='{% static "lib/css/nv.d3.min.css" %}'>#}
{% endblock css %}

{% block page_title %}Device{% endblock %}
{% block body_class %}{{ block.super }}{% endblock %}

{% block content %}

    <h1>Device {{ device_param }}</h1>
{#    <a href="{% url 'api:device_measurements' device_param.id %}">Link</a>#}
    <table>
        <tr>
            <td>Device Id</td>
            <td>{{ device_param.device.node.space_name }}</td>
        </tr>

    </table>

    <div id="chart">

    </div>

    <script type="text/javascript">
        {% url 'api:device_measurements' device_param.id as api_endpoint %}
        document.body.onload = function () {
            drawTemperatureChart('{{ api_endpoint }}');
        }
    </script>

{% endblock content %}

ep/templates/ep/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block css %}
    <link rel="stylesheet" href='{% static "css/index.css" %}'>
{% endblock css %}
{% block page_title %}Energy Portal Home{% endblock %}
{% block body_class %}{{ block.super }}{% endblock %}

{% block content %}

    <div class="col-xs-7 col-sm-7 col-md-8">
        <p>Welcome to the IODiCUS Energy Portal.</p>
    </div>
{% endblock content %}

ep/templates/ep/nologin.html
<h1>No login at the moment.</h1>